# Generated by Django 4.2.4 on 2023-08-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('connection', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'levels',
                'managed': False,
            },
        ),
    ]
